### ISSUE TITLE
Update changelog for version 3.0

### ISSUE THREAD

**Issue by gpgekko** [beaufortfrancois/extensions-update-notifier-chrome-extension#15]
On the webstore page, the changelog goes up to 2.3.1 while the latest version is 3.0

**Comment by beaufortfrancois** [comment]
I'd say it's a cache issue here.
What do you think?

**Comment by beaufortfrancois** [comment]
![screenshot 2015-02-18 at 4 04 14 pm](https://cloud.githubusercontent.com/assets/634478/6249491/d5a22a06-b787-11e4-940e-2d1c68c40ba5.png)

**Comment by gpgekko** [comment]
That's strange, I haven't opened the webstore page yet this week and cache
gets cleared each week, so there shouldn't be any cached resources. Even
now, clearing my cache / looking in incognito mode doesn't show the new
entry.

I guess it's the webstore being glitchy again.

**Comment by beaufortfrancois** [comment]
Maybe server caching there.
Can you try later and let me know?

**Comment by beaufortfrancois** [comment]
OOOH sorry I probably know what is happening there...
requirements for version 3.0 are chrome 42 (dev channel).

That may explain the weird behaviour.

**Comment by gpgekko** [comment]
Then there is another problem, because it updated to v3.0 on my m41 Beta
channel Chrome :P

**Comment by gpgekko** [comment]
Wait, scrap that, it was the Canary channel Chrome that updated the
extension. But still, I was using that to check out the webstore too... :S

**Comment by beaufortfrancois** [comment]
Woo! I almost had an attack there ;)
In which part of the globe are you right now?

**Comment by beaufortfrancois** [comment]
I've made some changes to the webstore item.
Does that solve the issue for you?

**Comment by gpgekko** [comment]
I'm in western Europe (Netherlands). I'll check my work computer tomorrow,
but from my home pc the webstore seems updated now.

**Comment by gpgekko** [comment]
Confirmed at work, changelog is updated here now. I'll just go ahead and close this, thanks!

**Comment by beaufortfrancois** [comment]
Thanks for reporting this bug Guylian.
Have a good day!
