### ISSUE TITLE
Version #3 of Extensions Update Notifier requires version 42.0.2296 of Chrome

### ISSUE THREAD

**Issue by LJB001** [beaufortfrancois/extensions-update-notifier-chrome-extension#17]
Chrome on Win7 and Win8.1 reports that the current version is: 40.0.2214.115 m and there is no option to get to version 42.0.2296.

See attached....

P.S.  Thanks for a GREAT extension.

**Comment by beaufortfrancois** [comment]
Yes, version 3 requires chrome 42 which is why you cannot install it.
As you can see at http://omahaproxy.appspot.com/, Dev Channel is on chrome 42 for the moment.
