### ISSUE TITLE
Update windows when you reinstall the extension

### ISSUE THREAD

**Issue by mikhaelkh** [beaufortfrancois/extensions-update-notifier-chrome-extension#20]
1) Install the extension, for example [this](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm), it updates frequently
2) Remove it
3) Wait until the new version is avalible
4) Install it again
Then update notification shows. This is kinda weird, why this extension remembers removed extensions?

**Comment by beaufortfrancois** [comment]
Thank you Michael for raising this issue.

You're right, I should clear local data storage when an extension is uninstalled.
I will update the extension and let you know when it's done.

**Comment by beaufortfrancois** [comment]
I've updated Extensions Update Notifier extension in the Chrome Web Store: https://chrome.google.com/webstore/detail/nlldbplhbaopldicmcoogopmkonpebjm

See https://github.com/beaufortfrancois/extensions-update-notifier-chrome-extension/commit/1d172b099b0bbbd4b16e39e3e6cb9fa7bb86a08b for more details.

Please reopen this issue if you're still experiencing some issues.
Thanks again!
