### ISSUE TITLE
Update notifications only appear for a while

### ISSUE THREAD

**Issue by ngyikp** [beaufortfrancois/extensions-update-notifier-chrome-extension#21]
Since Chrome 47 removed the notification center, the notifications just appear for a few seconds and then disappear forever, even if you are not in front of your computer.

There should be a history/archive feature so we can find see all previous updates.

**Comment by beaufortfrancois** [comment]
This is not a trivial change sadly.
In the mean time, I've made the notifications stay [longer](https://github.com/beaufortfrancois/extensions-update-notifier-chrome-extension/commit/9b7246e56bc5b8f55ac9423baf6865150a00facc) in the 3.4 updated version. Let me know how that plays out for you.

**Comment by beaufortfrancois** [comment]
The `requireInteraction` key is sadly not available in the [chrome.notifications API](https://developer.chrome.com/apps/notifications), only for Web Notifications. See https://googlechrome.github.io/samples/notifications/requireInteraction.html

I've filed a feature at https://code.google.com/p/chromium/issues/detail?id=574763

**Comment by beaufortfrancois** [comment]
I'll update the extension when Chrome 50 reaches stable channel with https://github.com/beaufortfrancois/extensions-update-notifier-chrome-extension/commit/90b93daee5fe40d7c9a1f3a570b1be5d21ad4777

**Comment by ngyikp** [comment]
ping

**Comment by beaufortfrancois** [comment]
Some Chrome OS devices are still stuck in Chrome 49 for now. (http://cros-omahaproxy.appspot.com/)
I'll wait a little bit more then.

**Comment by beaufortfrancois** [comment]
Tada! Chrome M50 is deployed to everyone. The extension has now been updated then: https://chrome.google.com/webstore/detail/nlldbplhbaopldicmcoogopmkonpebjm

Please reopen this issue if you're still experiencing some pain.
