### ISSUE TITLE
read changelog.md if available

### ISSUE THREAD

**Issue by thib3113** [beaufortfrancois/extensions-update-notifier-chrome-extension#23]
Maybe reading the changelog.md is a good things ?

So the developper don't need to update description with changelog ( maybe lambda people never read changelog ), but for other they can read the changelog.md ?

**Comment by beaufortfrancois** [comment]
For info, where did you see some changelog.md files for chrome web store extensions/apps?

**Comment by thib3113** [comment]
In the extension folder .

You can't access with chrome.filesystem ? (I never try to use this part of API)

**Comment by beaufortfrancois** [comment]
chrome.filesystem won't allow me to access other extension folders sadly.

**Comment by thib3113** [comment]
yes, i try some things with manager, but I can't found anything ... And I see on my computer, the only extension with changelog.md is mine .... this feature is useless for the moment ...
